version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: punto_venta
      MYSQL_USER: john
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: